## New MkDocs configuration (old version preserved in mkdocs_old.yml)
site_name: DragDropDeploy
site_description: Self-hosted drag & drop static site deployment platform
repo_url: https://github.com/TomKonig/DragDropDeploy
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
extra:
  version: unreleased
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TomKonig/DragDropDeploy
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - Quickstart: getting-started/quickstart.md
      - First Deployment Deep Dive: getting-started/first-deployment.md
  - User Guide:
      - Upload & Build Flags: operations/build-flags.md
      - Minification & Performance: operations/build-performance.md
      - Observability (Metrics): operations/observability.md
  - Admin Guide:
      - Docker Compose: operations/docker-compose.md
      - Coolify Deployment: operations/coolify.md
      - Manual Install: operations/manual-install.md
      - Release Process: operations/release-process.md
  - Architecture:
      - Overview Spec: architecture/spec.md
      - Build Pipeline: architecture/build-pipeline.md
      - Database: architecture/database.md
      - Documentation Structure: architecture/docs-structure.md
  - Reference:
      - Configuration: reference/configuration.md
      - Versioning: reference/versioning.md
      - Rollback: reference/rollback.md
      - Security Baseline: reference/security-baseline.md
      - API Authentication: reference/api-auth.md
      - API (Generated): reference/api.md
      - Changelog: reference/changelog.md
  - Development:
      - Testing Strategy: development/testing.md
      - Contributing: development/contributing.md
  - Security:
      - Threat Model: security/threat-model.md
  - Roadmap: roadmap.md
  - Troubleshooting: troubleshooting/index.md
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - codehilite