name: Docs Validation

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  docs-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm install --no-audit --no-fund
      - name: Run docs checks
        env:
          GH_TOKEN: ${{ github.token }}
        run: npm run docs:check
      - name: Roadmap docs sync check
        env:
          GH_TOKEN: ${{ github.token }}
        run: node scripts/docs/check-roadmap-sync.js
