name: Roadmap Consistency

on:
  push:
    paths:
      - roadmap.yaml
      - scripts/validate-roadmap.cjs
      - .github/workflows/roadmap-validate.yml
      - "**/agent-guidelines.md"
  pull_request:
    paths:
      - roadmap.yaml
      - scripts/validate-roadmap.cjs
      - .github/workflows/roadmap-validate.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm ci --omit=dev || true
          npm ls yaml >/dev/null 2>&1 || npm i yaml
      - name: Validate roadmap
        env:
          # Provide both variable names; gh CLI auto-uses GITHUB_TOKEN. If you define a repository secret GH_TOKEN (a PAT) it will be used by scripts via fallback logic.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          node scripts/validate-roadmap.cjs
